#!/usr/bin/env bash

if [ -n "$AWS_BUCKET" ]; then
  cat << EOF > .s3cfg
[default]
access_key = ${AWS_ACCESS_KEY}
secret_key = ${AWS_SECRET_KEY}
EOF
  if [ -d world ]; then
    s3cmd sync world/ s3://${AWS_BUCKET}/world/
    s3cmd sync plugins/ s3://${AWS_BUCKET}/plugins/
  else
    mkdir -p world
    cd world
    s3cmd get --recursive s3://${AWS_BUCKET}/world/
    s3cmd get --recursive s3://${AWS_BUCKET}/plugins/
    cd ..
  fi
  rm .s3cfg
fi

if [ -n "$DROPBBOX_ACCESS_TOKEN" ]; then
  cat << EOF > .dropbox_uploader
OAUTH_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
EOF
  if [ -d world ]; then
    bin/dropbox_uploader.sh upload world/ /world
    bin/dropbox_uploader.sh upload plugins/ /plugins
  else
    mkdir -p world
    cd world
    bin/dropbox_uploader.sh download /world
    bin/dropbox_uploader.sh download /plugins
    cd ..
  fi
  rm .dropbox_uploader
fi
